# Chapter1. 신경망 복습

## 1.1 수학과 파이썬 복습

### 1.1.1 벡터와 행렬

* 벡터 : 크기와 방향을 가진 양
* 행렬 : 숫자가 2차원 형태로 늘어선 것

<img src="./images/1-1.png" width="300" height="300"/>
[1-1]

* 텐서 : 벡터와 행렬을 확장하여 숫자 집합을 N차원으로 표현

<img src="./images/1-2.png" width="300" height="300"/>
[1-2]

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
x.__class__

numpy.ndarray

In [4]:
x.shape

(3,)

In [5]:
x.ndim

1

In [6]:
W = np.array([[1,2,3],[4,5,6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

### 1.1.2 행렬의 원소별 연산

In [9]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [10]:
W * X # 행렬 같은 자리별 곱셈이 이뤄짐

array([[ 0,  2,  6],
       [12, 20, 30]])

### 1.1.3 브로드캐스트

In [11]:
A = np.array([[1,2],[3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [12]:
A = np.array([[1,2],[3,4]])
b = np.array([10, 20])

In [13]:
A * b

array([[10, 40],
       [30, 80]])

### 1.1.4 벡터의 내적과 행렬의 곱

<img src="./images/1.1.png" width="200" height="200"/>
[1.1]

<img src="./images/1-5.png" width="300" height="300"/>
[1-5]

In [14]:
# 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [15]:
# 행렬곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B) # matrix mul

array([[19, 22],
       [43, 50]])

In [16]:
np.dot(A,B) # matrix mul

array([[19, 22],
       [43, 50]])

#### 잠깐! (dot 과 matmul의 차이)

* 2차원 이하의 행렬곱에서는 결과 동일
* 3차원 이상의 행렬끼리 곱할 때 다른 결과를 보여줌
* np.dot(a, b)는 a의 마지막 axis와 b의 마지막에서 두번째 axis끼리 곱한 결과를 반영하고, np.matmul(a, b)는 a의 마지막 두 axis 차원이 (n, k), b의 마지막 두 axis 차원이 (k, m) 일 때, 이 사이에서만 곱하여 (n, m) 차원이 되도록 반영


In [17]:
A = np.arange(2*3*4).reshape((2,3,4))
B = np.arange(2*3*4).reshape((2,4,3))

In [18]:
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
B

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [20]:
np.dot(A,B).shape

(2, 3, 2, 3)

In [21]:
np.matmul(A,B).shape

(2, 3, 3)

In [22]:
np.dot(A,B)

array([[[[  42,   48,   54],
         [ 114,  120,  126]],

        [[ 114,  136,  158],
         [ 378,  400,  422]],

        [[ 186,  224,  262],
         [ 642,  680,  718]]],


       [[[ 258,  312,  366],
         [ 906,  960, 1014]],

        [[ 330,  400,  470],
         [1170, 1240, 1310]],

        [[ 402,  488,  574],
         [1434, 1520, 1606]]]])

In [23]:
np.matmul(A,B)

array([[[  42,   48,   54],
        [ 114,  136,  158],
        [ 186,  224,  262]],

       [[ 906,  960, 1014],
        [1170, 1240, 1310],
        [1434, 1520, 1606]]])

### 1.1.5 행렬 형상 확인

<img src="./images/1-6.png" width="400" height="400"/>
[1-6]

## 1.2 신경망의 추론

### 1.2.1 신경망 추론 전체 그림

<img src="./images/1-7.png" width="300" height="300"/>
[1-7]

* 완전연결계층 : 인전합는 츠으이 모든 뉴런과 연결되어 있는 신경망

#### (수식) 입력 데이터 : $(x_1, x_2)$ 가중치 : $w_{11}, w_{12}$ 편향 : $b_1$

<img src="./images/1.2.png" width="150" height="150"/>
[1.2]

(예시)

<img src="./images/1.3.png" width="400" height="400"/>
[1.3]

<img src="./images/1.4.png" width="100" height="100"/>
[1.4]

#### (입력데이터가 1개)

<img src="./images/1-8.png" width="300" height="300"/>
[1-8]

#### (1개의 입력데이터가 아니라 N개의 입력데이터라면)

<img src="./images/1-9.png" width="300" height="300"/>
[1-9]

In [24]:
## 완전연결계층 미니배치

In [25]:
import numpy as np
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.matmul(x, W1) + b1

In [26]:
h

array([[ 1.34305574,  0.41253056,  1.17292385, -0.32953274],
       [-1.35952875,  0.27462458,  1.221535  , -0.32332931],
       [ 2.55740572,  0.37186856,  1.0654311 , -0.34309867],
       [ 1.13130738, -0.03402714,  0.81306313, -0.37481217],
       [-1.64814735,  1.08746264,  1.91739391, -0.23575072],
       [-0.24625871,  0.98078358,  1.74344499, -0.2576857 ],
       [ 1.09650525,  0.49464295,  1.25638736, -0.31902154],
       [ 1.85516481,  1.45784385,  2.01429866, -0.22366739],
       [ 2.62806579, -0.08401864,  0.6806778 , -0.39151966],
       [-0.21612297, -0.21296684,  0.74534235, -0.3832915 ]])

#### (완전연결계층에 의한 변환 : 선형 변환 / 비선형 효과 부여 : 활성화 함수)

* 예시 
    * 시그모이드 함수

<img src="./images/1.5.png" width="200" height="200"/>
[1.5]

<img src="./images/1-10.png" width="300" height="300"/>
[1-10]

In [27]:
## 시그모이드 함수 구현

In [28]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [29]:
a = sigmoid(h)

In [30]:
a

array([[0.79299201, 0.6016945 , 0.76367311, 0.41835432],
       [0.2043169 , 0.56822788, 0.77233357, 0.41986459],
       [0.92806947, 0.59191041, 0.74372707, 0.41505697],
       [0.75608009, 0.49149404, 0.69276185, 0.40737875],
       [0.1613595 , 0.74790362, 0.87184754, 0.44133378],
       [0.43874457, 0.72726367, 0.85112411, 0.4359327 ],
       [0.74960472, 0.62119958, 0.77840359, 0.42091423],
       [0.86473237, 0.81120268, 0.88229019, 0.44431511],
       [0.93264615, 0.47900769, 0.66388996, 0.40335153],
       [0.44617859, 0.44695861, 0.67816297, 0.40533327]])

### 1.2.2 계층으로 클래스화 및 순전파 구현

* (구현 규칙)
    * 모든 계층은 forward(), backward() 메서드를 가진다
        * forward : 순전파 
        * backward : 역전파
    * 모든 계층은 인스턴스 변수인 params, grads를 가진다
        * params : 가중치와 편향 등 매개변수 담는 리스트
        * grads : params에 저장된 각 매개변수에 대응하여 해당 매개변수의 기울기를 보관하는 리스트

#### (이 절에서는 순전파만 구현)

In [31]:
# Sigmoid 계층 구현

In [32]:
import numpy as np

In [41]:
class Sigmoid:
    def __init__(self):
        self.params = []
    
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [40]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params.W, self,params.b ### 리스트는 사이즈가 같을 때 각각의 번지의 값을 바로 넣을 수 있다
        out = np.matmul(x,W) + b
        return out

<img src="./images/1-11.png" width="400" height="400"/>
[1-11]

In [57]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # 가중치와 편향 초기화
        W1 = np.random.randn(I,H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H,O)
        b2 = np.random.randn(O)
        
        # 계층 생성
        self.layers = [Affine(W1, b1), Sigmoid(), Affine(W2, b2)]
        
        # 모든 가중치를 리스트에 모은다
        self.params = []
        for layer in self.layers:
            self.params += lalyer.params ## extend와 같은 듯
            
        def predict(self, x):
            for layer in self.layers:
                x = layer.forward(x)
                
            return x