# Chapter1. 신경망 복습

## 1.1 수학과 파이썬 복습

### 1.1.1 벡터와 행렬

* 벡터 : 크기와 방향을 가진 양
* 행렬 : 숫자가 2차원 형태로 늘어선 것

<img src="./images/1-1.png" width="300" height="300"/>
[1-1]

* 텐서 : 벡터와 행렬을 확장하여 숫자 집합을 N차원으로 표현

<img src="./images/1-2.png" width="300" height="300"/>
[1-2]

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
x.__class__

numpy.ndarray

In [4]:
x.shape

(3,)

In [5]:
x.ndim

1

In [6]:
W = np.array([[1,2,3],[4,5,6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

### 1.1.2 행렬의 원소별 연산

In [9]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W * X # 행렬 같은 자리별 곱셈이 이뤄짐

array([[ 0,  2,  6],
       [12, 20, 30]])

### 1.1.3 브로드캐스트

In [12]:
A = np.array([[1,2],[3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [13]:
A = np.array([[1,2],[3,4]])
b = np.array([10, 20])

In [14]:
A * b

array([[10, 40],
       [30, 80]])

### 1.1.4 벡터의 내적과 행렬의 곱

<img src="./images/1.1.png" width="200" height="200"/>
[1.1]

<img src="./images/1-5.png" width="300" height="300"/>
[1-5]

In [15]:
# 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [16]:
# 행렬곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B) # matrix mul

array([[19, 22],
       [43, 50]])

In [17]:
np.dot(A,B) # matrix mul

array([[19, 22],
       [43, 50]])

#### 잠깐! (dot 과 matmul의 차이)

* 2차원 이하의 행렬곱에서는 결과 동일
* 3차원 이상의 행렬끼리 곱할 때 다른 결과를 보여줌
* np.dot(a, b)는 a의 마지막 axis와 b의 마지막에서 두번째 axis끼리 곱한 결과를 반영하고, np.matmul(a, b)는 a의 마지막 두 axis 차원이 (n, k), b의 마지막 두 axis 차원이 (k, m) 일 때, 이 사이에서만 곱하여 (n, m) 차원이 되도록 반영


In [22]:
A = np.arange(2*3*4).reshape((2,3,4))
B = np.arange(2*3*4).reshape((2,4,3))

In [23]:
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
B

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [25]:
np.dot(A,B).shape

(2, 3, 2, 3)

In [27]:
np.matmul(A,B).shape

(2, 3, 3)

In [28]:
np.dot(A,B)

array([[[[  42,   48,   54],
         [ 114,  120,  126]],

        [[ 114,  136,  158],
         [ 378,  400,  422]],

        [[ 186,  224,  262],
         [ 642,  680,  718]]],


       [[[ 258,  312,  366],
         [ 906,  960, 1014]],

        [[ 330,  400,  470],
         [1170, 1240, 1310]],

        [[ 402,  488,  574],
         [1434, 1520, 1606]]]])

In [29]:
np.matmul(A,B)

array([[[  42,   48,   54],
        [ 114,  136,  158],
        [ 186,  224,  262]],

       [[ 906,  960, 1014],
        [1170, 1240, 1310],
        [1434, 1520, 1606]]])

### 1.1.5 행렬 형상 확인

<img src="./images/1-6.png" width="400" height="400"/>
[1-6]

## 1.2 신경망의 추론

### 1.2.1 신경망 추론 전체 그림

<img src="./images/1-7.png" width="300" height="300"/>
[1-7]

* 완전연결계층 : 인전합는 츠으이 모든 뉴런과 연결되어 있는 신경망

#### (수식) 입력 데이터 : $(x_1, x_2)$ 가중치 : $w_{11}, w_{12}$ 편향 : $b_1$

<img src="./images/1.2.png" width="150" height="150"/>
[1.2]

(예시)

<img src="./images/1.3.png" width="400" height="400"/>
[1.3]

<img src="./images/1.4.png" width="100" height="100"/>
[1.4]

#### (입력데이터가 1개)

<img src="./images/1-8.png" width="300" height="300"/>
[1-8]

#### (1개의 입력데이터가 아니라 N개의 입력데이터라면)

<img src="./images/1-9.png" width="300" height="300"/>
[1-9]

In [31]:
## 완전연결계층 미니배치

In [32]:
import numpy as np
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.matmul(x, W1) + b1

In [33]:
h

array([[-3.43935497, -2.74053833,  2.63109766, -0.72953733],
       [-5.02001551, -3.63558244,  2.58472758,  2.48241013],
       [-4.23289736, -3.22374163,  2.6689891 ,  0.69807949],
       [-0.8825587 , -0.58436365,  1.42642023, -2.0572704 ],
       [-4.25716071, -2.92266396,  2.09957668,  2.46623978],
       [-4.77828996, -3.70673495,  2.96761254,  0.85540759],
       [-2.7796635 , -2.15725528,  2.27157484, -0.92492566],
       [-2.29847464, -1.36562771,  1.34786182,  0.93180539],
       [-2.47684525, -1.60889294,  1.59962093,  0.51752057],
       [ 0.6443256 ,  1.30724757, -0.38404343,  0.44743435]])

#### (완전연결계층에 의한 변환 : 선형 변환 / 비선형 효과 부여 : 활성화 함수)

* 예시 
    * 시그모이드 함수

<img src="./images/1.5.png" width="200" height="200"/>
[1.5]

<img src="./images/1-10.png" width="300" height="300"/>
[1-10]

In [36]:
## 시그모이드 함수 구현

In [37]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [38]:
a = sigmoid(h)

In [39]:
a

array([[0.03108791, 0.06062324, 0.93283635, 0.32529627],
       [0.00656109, 0.02569113, 0.92987218, 0.92289947],
       [0.01430275, 0.03828199, 0.93517177, 0.66776183],
       [0.29264783, 0.35792914, 0.80634293, 0.11331981],
       [0.01396468, 0.05104451, 0.89086203, 0.92174095],
       [0.00834022, 0.02396895, 0.95108934, 0.70170028],
       [0.05843307, 0.10365519, 0.90649536, 0.28395532],
       [0.09124937, 0.20332717, 0.79377984, 0.71744142],
       [0.07749744, 0.16674237, 0.8319654 , 0.62656781],
       [0.65573061, 0.78705221, 0.40515204, 0.61002905]])

### 1.2.2 계층으로 클래스화 및 순전파 구현